/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Application: () => import('#controllers/application_controller'),
  Auth: () => import('#controllers/auth_controller'),
  LandlordDashboards: () => import('#controllers/landlord_dashboards_controller'),
  Setups: () => import('#controllers/setups_controller'),
  StudentDashboards: () => import('#controllers/student_dashboards_controller'),
}
