/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accommodation: () => import('#controllers/accommodation_controller'),
  AdminVerifications: () => import('#controllers/admin_verifications_controller'),
  Application: () => import('#controllers/application_controller'),
  Auth: () => import('#controllers/auth_controller'),
  LandlordDashboards: () => import('#controllers/landlord_dashboards_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Setups: () => import('#controllers/setups_controller'),
  StudentDashboards: () => import('#controllers/student_dashboards_controller'),
}
