import { UserSeedData, FileMetadataSeedData, StudentSeedData, makeEnrollmentProof } from "./users.ts";

/*
    Fake Users and Students data generated by Claude (thanks claude)

    For testing purposes only
*/

export const FakeUsers: UserSeedData[] = [
    { email: 'aabad@up.edu.ph', fname: 'Andrea', lname: 'Abad', role: 'student' },
    { email: 'balonzo@up.edu.ph', fname: 'Bryan', lname: 'Alonzo', role: 'student' },
    { email: 'caquino@up.edu.ph', fname: 'Christine', lname: 'Aquino', role: 'student' },
    { email: 'darevalo@up.edu.ph', fname: 'Daniel', lname: 'Arevalo', role: 'student' },
    { email: 'eavila@up.edu.ph', fname: 'Elaine', lname: 'Avila', role: 'student' },
    { email: 'bbautista@up.edu.ph', fname: 'Bea', lname: 'Bautista', role: 'student' },
    { email: 'cbernardo@up.edu.ph', fname: 'Carl', lname: 'Bernardo', role: 'student' },
    { email: 'dborja@up.edu.ph', fname: 'Dianne', lname: 'Borja', role: 'student' },
    { email: 'ecruz@up.edu.ph', fname: 'Ethan', lname: 'Cruz', role: 'student' },
    { email: 'fcastro@up.edu.ph', fname: 'Franz', lname: 'Castro', role: 'student' },

    { email: 'ggarcia@up.edu.ph', fname: 'Grace', lname: 'Garcia', role: 'student' },
    { email: 'hherrera@up.edu.ph', fname: 'Harold', lname: 'Herrera', role: 'student' },
    { email: 'iignacio@up.edu.ph', fname: 'Ian', lname: 'Ignacio', role: 'student' },
    { email: 'jjimenez@up.edu.ph', fname: 'Jessa', lname: 'Jimenez', role: 'student' },
    { email: 'kkho@up.edu.ph', fname: 'Kevin', lname: 'Kho', role: 'student' },
    { email: 'llim@up.edu.ph', fname: 'Lara', lname: 'Lim', role: 'student' },
    { email: 'mmendoza@up.edu.ph', fname: 'Mark', lname: 'Mendoza', role: 'student' },
    { email: 'nnavarro@up.edu.ph', fname: 'Nicole', lname: 'Navarro', role: 'student' },
    { email: 'ooliveros@up.edu.ph', fname: 'Oscar', lname: 'Oliveros', role: 'student' },
    { email: 'pperez@up.edu.ph', fname: 'Paula', lname: 'Perez', role: 'student' },

    { email: 'qquimbo@up.edu.ph', fname: 'Quincy', lname: 'Quimbo', role: 'student' },
    { email: 'rreyes@up.edu.ph', fname: 'Ralph', lname: 'Reyes', role: 'student' },
    { email: 'ssantos@up.edu.ph', fname: 'Samantha', lname: 'Santos', role: 'student' },
    { email: 'ttorres@up.edu.ph', fname: 'Theo', lname: 'Torres', role: 'student' },
    { email: 'uuy@up.edu.ph', fname: 'Ulysses', lname: 'Uy', role: 'student' },
    { email: 'vvaldez@up.edu.ph', fname: 'Vanessa', lname: 'Valdez', role: 'student' },
    { email: 'wwong@up.edu.ph', fname: 'Wendy', lname: 'Wong', role: 'student' },
    { email: 'xxavier@up.edu.ph', fname: 'Xander', lname: 'Xavier', role: 'student' },
    { email: 'yyap@up.edu.ph', fname: 'Yasmin', lname: 'Yap', role: 'student' },
    { email: 'zzamora@up.edu.ph', fname: 'Zack', lname: 'Zamora', role: 'student' },

    { email: 'aagustin@up.edu.ph', fname: 'Aly', lname: 'Agustin', role: 'student' },
    { email: 'bbalmes@up.edu.ph', fname: 'Ben', lname: 'Balmes', role: 'student' },
    { email: 'ccapili@up.edu.ph', fname: 'Chloe', lname: 'Capili', role: 'student' },
    { email: 'ddelao@up.edu.ph', fname: 'David', lname: 'Delao', role: 'student' },
    { email: 'eespino@up.edu.ph', fname: 'Ella', lname: 'Espino', role: 'student' },
    { email: 'fferrer@up.edu.ph', fname: 'Fred', lname: 'Ferrer', role: 'student' },
    { email: 'gguinto@up.edu.ph', fname: 'Gina', lname: 'Guinto', role: 'student' },
    { email: 'hhizon@up.edu.ph', fname: 'Hector', lname: 'Hizon', role: 'student' },
    { email: 'iibanez@up.edu.ph', fname: 'Isabel', lname: 'Ibanez', role: 'student' },
    { email: 'jjacinto@up.edu.ph', fname: 'Jake', lname: 'Jacinto', role: 'student' },

    { email: 'kkatigbak@up.edu.ph', fname: 'Karla', lname: 'Katigbak', role: 'student' },
    { email: 'llopez@up.edu.ph', fname: 'Liam', lname: 'Lopez', role: 'student' },
    { email: 'mmiranda@up.edu.ph', fname: 'Mika', lname: 'Miranda', role: 'student' },
    { email: 'nnieva@up.edu.ph', fname: 'Noel', lname: 'Nieva', role: 'student' },
    { email: 'oortega@up.edu.ph', fname: 'Olive', lname: 'Ortega', role: 'student' },
    { email: 'ppanganiban@up.edu.ph', fname: 'Paul', lname: 'Panganiban', role: 'student' },
    { email: 'qquisumbing@up.edu.ph', fname: 'Queen', lname: 'Quisumbing', role: 'student' },
    { email: 'rrivera@up.edu.ph', fname: 'Rina', lname: 'Rivera', role: 'student' },
    { email: 'ssoriano@up.edu.ph', fname: 'Sean', lname: 'Soriano', role: 'student' },
    { email: 'ttan@up.edu.ph', fname: 'Trisha', lname: 'Tan', role: 'student' },

    { email: 'uumali@up.edu.ph', fname: 'Uno', lname: 'Umali', role: 'student' },
    { email: 'vvillanueva@up.edu.ph', fname: 'Vince', lname: 'Villanueva', role: 'student' },
    { email: 'wwenceslao@up.edu.ph', fname: 'Warren', lname: 'Wenceslao', role: 'student' },
    { email: 'xxu@up.edu.ph', fname: 'Xenia', lname: 'Xu', role: 'student' },
    { email: 'yyumul@up.edu.ph', fname: 'Yuri', lname: 'Yumul', role: 'student' },
    { email: 'zzulueta@up.edu.ph', fname: 'Zia', lname: 'Zulueta', role: 'student' },

    { email: 'aalcantara@up.edu.ph', fname: 'Aaron', lname: 'Alcantara', role: 'student' },
    { email: 'bbarrios@up.edu.ph', fname: 'Bianca', lname: 'Barrios', role: 'student' },
    { email: 'ccoronel@up.edu.ph', fname: 'Cedric', lname: 'Coronel', role: 'student' },
    { email: 'ddizon@up.edu.ph', fname: 'Daisy', lname: 'Dizon', role: 'student' },
    { email: 'eevangelista@up.edu.ph', fname: 'Eli', lname: 'Evangelista', role: 'student' },
    { email: 'fflores@up.edu.ph', fname: 'Faith', lname: 'Flores', role: 'student' },
    { email: 'ggatchalian@up.edu.ph', fname: 'Gab', lname: 'Gatchalian', role: 'student' },
    { email: 'hhilario@up.edu.ph', fname: 'Hannah', lname: 'Hilario', role: 'student' },
    { email: 'iisidro@up.edu.ph', fname: 'Ivan', lname: 'Isidro', role: 'student' },
    { email: 'jjavier@up.edu.ph', fname: 'Julia', lname: 'Javier', role: 'student' },

    { email: 'kkintanar@up.edu.ph', fname: 'Karl', lname: 'Kintanar', role: 'student' },
    { email: 'llacson@up.edu.ph', fname: 'Lea', lname: 'Lacson', role: 'student' },
    { email: 'mmallari@up.edu.ph', fname: 'Miguel', lname: 'Mallari', role: 'student' },
    { email: 'nnoble@up.edu.ph', fname: 'Nina', lname: 'Noble', role: 'student' },
    { email: 'oocampo@up.edu.ph', fname: 'Omar', lname: 'Ocampo', role: 'student' },
    { email: 'ppadilla@up.edu.ph', fname: 'Pat', lname: 'Padilla', role: 'student' },
    { email: 'qquizon@up.edu.ph', fname: 'Queenie', lname: 'Quizon', role: 'student' },
    { email: 'rrosales@up.edu.ph', fname: 'Rico', lname: 'Rosales', role: 'student' },
    { email: 'ssy@up.edu.ph', fname: 'Sophia', lname: 'Sy', role: 'student' },
    { email: 'ttulfo@up.edu.ph', fname: 'Tom', lname: 'Tulfo', role: 'student' },

    { email: 'uubaldo@up.edu.ph', fname: 'Una', lname: 'Ubaldo', role: 'student' },
    { email: 'vvergara@up.edu.ph', fname: 'Victor', lname: 'Vergara', role: 'student' },
    { email: 'wwu@up.edu.ph', fname: 'Willa', lname: 'Wu', role: 'student' },
    { email: 'xxenon@up.edu.ph', fname: 'Xy', lname: 'Xenon', role: 'student' },
    { email: 'yynares@up.edu.ph', fname: 'Yen', lname: 'Ynares', role: 'student' },
    { email: 'zzubiri@up.edu.ph', fname: 'Zed', lname: 'Zubiri', role: 'student' },

    { email: 'aarellano@up.edu.ph', fname: 'Aira', lname: 'Arellano', role: 'student' },
    { email: 'bbondoc@up.edu.ph', fname: 'Brent', lname: 'Bondoc', role: 'student' },
    { email: 'ccuenca@up.edu.ph', fname: 'Cara', lname: 'Cuenca', role: 'student' },
    { email: 'ddumlao@up.edu.ph', fname: 'Duke', lname: 'Dumlao', role: 'student' },
    { email: 'eestrada@up.edu.ph', fname: 'Erin', lname: 'Estrada', role: 'student' },
    { email: 'ffajardo@up.edu.ph', fname: 'Finn', lname: 'Fajardo', role: 'student' },
    { email: 'ggalang@up.edu.ph', fname: 'Gail', lname: 'Galang', role: 'student' },
    { email: 'hhabana@up.edu.ph', fname: 'Hans', lname: 'Habana', role: 'student' },
    { email: 'iidalgo@up.edu.ph', fname: 'Ina', lname: 'Idalgo', role: 'student' },
    { email: 'jjose@up.edu.ph', fname: 'Jared', lname: 'Jose', role: 'student' },

    { email: 'kkyle@up.edu.ph', fname: 'Kaye', lname: 'Kyle', role: 'student' },
    { email: 'llorenzo@up.edu.ph', fname: 'Luis', lname: 'Lorenzo', role: 'student' },
    { email: 'mmata@up.edu.ph', fname: 'Mara', lname: 'Mata', role: 'student' },
    { email: 'nnicolas@up.edu.ph', fname: 'Neil', lname: 'Nicolas', role: 'student' },
    { email: 'oorquia@up.edu.ph', fname: 'Ona', lname: 'Orquia', role: 'student' },
    { email: 'ppuno@up.edu.ph', fname: 'Pio', lname: 'Puno', role: 'student' },
    { email: 'qquiambao@up.edu.ph', fname: 'Quinn', lname: 'Quiambao', role: 'student' },
    { email: 'rrabena@up.edu.ph', fname: 'Rae', lname: 'Rabena', role: 'student' },
    { email: 'ssunga@up.edu.ph', fname: 'Sam', lname: 'Sunga', role: 'student' },
    { email: 'ttiongson@up.edu.ph', fname: 'Tina', lname: 'Tiongson', role: 'student' }
]

export const FakeStudents: StudentSeedData[] = FakeUsers.map((user, index) => ({
    email: user.email,
    studentNumber: `2023-${String(70001 + index).padStart(5, '0')}`,
    college: 'cas',
    degreeProgram: 'BS Computer Science',
    gender: index % 2 === 0 ? 'female' : 'male'
}));

export const FakeEnrollmentProofs: FileMetadataSeedData[] = FakeUsers.map((user) =>
    makeEnrollmentProof(user)
);