import { DormSeedData } from "./uplb_dorms_data.ts";

const scholars_dormitory: DormSeedData = {
    accommodation_name: "Scholar's Dormitory UPLB",
    accommodation_location:
        'G. Viado St., College, Los Baños, Laguna 4031',
    latitude: 14.165800,
    longitude: 121.239500,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 80,
    walking_distance: 8,
    biking_distance: 3,
    driving_distance: 2,
    application_start_date: '2026-06-01',
    application_end_date: '2026-08-31',
    images: [
        'scholars_dorm_front.jpg',
        'scholars_dorm_room.jpg',
        'scholars_dorm_common.jpg',
    ],
    tags: [
        'Private dorm',
        'Near UPLB gate',
        'Affordable rates',
        'Security personnel',
        'WiFi included',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        preferences: ['Near comfort room'],
        },
        {
        room_number: '102',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        preferences: ['Upper floor', 'Window view'],
        },
        {
        room_number: '202',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        },
    ],
}

const ccp_hostel: DormSeedData = {
    accommodation_name: 'CCP Hostel',
    accommodation_location:
        'Silangan Road, College, Los Baños, Laguna 4031',
    latitude: 14.164500,
    longitude: 121.238700,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 60,
    walking_distance: 12,
    biking_distance: 5,
    driving_distance: 3,
    images: [
        'ccp_hostel_front.jpg',
        'ccp_hostel_room.jpg',
        'ccp_hostel_common.jpg',
    ],
    tags: [
        'Private dorm',
        'Furnished rooms',
        'Coed',
        'Near Silangan gate',
        'Various room types',
    ],
    rooms: [
        {
        room_number: 'S-01',
        room_building: 'CCP Hostel',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 3500,
        tenant_restriction: 'coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'D-01',
        room_building: 'CCP Hostel',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'SH01',
        room_building: 'CCP Hostel',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2200,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'SH02',
        room_building: 'CCP Hostel',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 5,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
    ],
}

const arable_premier_residences: DormSeedData = {
    accommodation_name: 'Arable Premier Residences',
    accommodation_location:
        'Jose R. Velasco Ave., Batong Malake, Los Baños, Laguna 4031',
    latitude: 14.169800,
    longitude: 121.244200,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 50,
    walking_distance: 5,
    biking_distance: 2,
    driving_distance: 2,
    application_start_date: '2026-06-01',
    application_end_date: '2026-09-30',
    images: [
        'arable_front.jpg',
        'arable_room_single.jpg',
        'arable_room_double.jpg',
        'arable_bathroom.jpg',
    ],
    tags: [
        'Private dorm',
        'Aircon',
        'En-suite bathroom',
        'Hot shower',
        'WiFi',
        'Near main gate',
        'Modern facility',
    ],
    rooms: [
        {
        room_number: 'S-01',
        room_building: 'Arable Building',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 8000,
        tenant_restriction: 'coed',
        room_size: 15,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'TV',
            'Cabinet',
        ],
        preferences: ['Ground floor', 'Quiet room'],
        },
        {
        room_number: 'S-02',
        room_building: 'Arable Building',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 8000,
        tenant_restriction: 'coed',
        room_size: 15,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'TV',
            'Cabinet',
        ],
        },
        {
        room_number: 'D-01',
        room_building: 'Arable Building',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 6000,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'Cabinet',
        ],
        },
        {
        room_number: 'D-02',
        room_building: 'Arable Building',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 6000,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'Cabinet',
        ],
        },
        {
        room_number: 'T-01',
        room_building: 'Arable Building',
        room_type: 'shared',
        room_stay_type: 'transient',
        room_capacity: 3,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 9000, // ~3,000/night × ~3-night minimum
        tenant_restriction: 'coed',
        room_size: 22,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Towels',
            'Cabinet',
        ],
        },
    ],
}

export const PRIVATE_DORMS: DormSeedData[] = [
    scholars_dormitory,
    ccp_hostel,
    arable_premier_residences
]