import { DormSeedData } from "./uplb_dorms_data.ts";

const scholars_dormitory: DormSeedData = {
    accommodation_name: "Scholar's Dormitory UPLB",
    accommodation_location:
        'G. Viado St., College, Los Baños, Laguna 4031',
    latitude: 14.165800,
    longitude: 121.239500,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 80,
    walking_distance: 8,
    biking_distance: 3,
    driving_distance: 2,
    application_start_date: '2026-06-01',
    application_end_date: '2026-08-31',
    images: [
        'scholars_dorm_front.jpg',
        'scholars_dorm_room.jpg',
    ],
    tags: [
        'Private dorm',
        'Near UPLB gate',
        'Affordable rates',
        'Security personnel',
        'WiFi included',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        preferences: ['Near comfort room'],
        },
        {
        room_number: '102',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        preferences: ['Upper floor', 'Window view'],
        },
        {
        room_number: '202',
        room_building: "Scholar's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Electric fan'],
        },
    ],
}

const ccp_hostel: DormSeedData = {
    accommodation_name: 'CCP Hostel',
    accommodation_location:
        'Silangan Road, College, Los Baños, Laguna 4031',
    latitude: 14.164500,
    longitude: 121.238700,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 60,
    walking_distance: 12,
    biking_distance: 5,
    driving_distance: 3,
    images: [
        'ccp_hostel_front.jpg',
        'ccp_hostel_room.jpg',
        'ccp_hostel_common.jpg',
    ],
    tags: [
        'Private dorm',
        'Furnished rooms',
        'Coed',
        'Near Silangan gate',
        'Various room types',
    ],
    rooms: [
        {
        room_number: 'S-01',
        room_building: 'CCP Hostel',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 3500,
        tenant_restriction: 'coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'D-01',
        room_building: 'CCP Hostel',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'SH01',
        room_building: 'CCP Hostel',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2200,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
        {
        room_number: 'SH02',
        room_building: 'CCP Hostel',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 5,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 2,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Study desk', 'Cabinet', 'WiFi', 'Shared bathroom'],
        },
    ],
}

const arable_premier_residences: DormSeedData = {
    accommodation_name: 'Arable Premier Residences',
    accommodation_location:
        'Jose R. Velasco Ave., Batong Malake, Los Baños, Laguna 4031',
    latitude: 14.169800,
    longitude: 121.244200,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 50,
    walking_distance: 5,
    biking_distance: 2,
    driving_distance: 2,
    application_start_date: '2026-06-01',
    application_end_date: '2026-09-30',
    images: [
        'arable_front.jpg',
        'arable_room_single.jpg',
        'arable_room_double.jpg',
        'arable_bathroom.jpg',
    ],
    tags: [
        'Private dorm',
        'Aircon',
        'En-suite bathroom',
        'Hot shower',
        'WiFi',
        'Near main gate',
        'Modern facility',
    ],
    rooms: [
        {
        room_number: 'S-01',
        room_building: 'Arable Building',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 8000,
        tenant_restriction: 'coed',
        room_size: 15,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'TV',
            'Cabinet',
        ],
        preferences: ['Ground floor', 'Quiet room'],
        },
        {
        room_number: 'S-02',
        room_building: 'Arable Building',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 8000,
        tenant_restriction: 'coed',
        room_size: 15,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'TV',
            'Cabinet',
        ],
        },
        {
        room_number: 'D-01',
        room_building: 'Arable Building',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 6000,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'Cabinet',
        ],
        },
        {
        room_number: 'D-02',
        room_building: 'Arable Building',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 6000,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Microwave access',
            'Cabinet',
        ],
        },
        {
        room_number: 'T-01',
        room_building: 'Arable Building',
        room_type: 'shared',
        room_stay_type: 'transient',
        room_capacity: 3,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 9000, // ~3,000/night × ~3-night minimum
        tenant_restriction: 'coed',
        room_size: 22,
        inclusions: [
            'Aircon',
            'En-suite bathroom',
            'Hot shower',
            'WiFi',
            'Drinking water',
            'Towels',
            'Cabinet',
        ],
        },
    ],
}

// commented out for now (name taken)
// const one_silangan: DormSeedData = {
//     accommodation_name: 'One Silangan Place',
//     accommodation_location:
//         'Silangan, near UPLB Main Gate, College, Los Baños, Laguna',
//     latitude: 14.165200,
//     longitude: 121.238000,
//     accommodation_type: 'off-campus',
//     tenant_restriction: 'coed',
//     accommodation_capacity: 40,
//     walking_distance: 6,
//     biking_distance: 3,
//     driving_distance: 2,
//     images: [
//         'one_silangan_front.jpg',
//         'one_silangan_room_ac.jpg',
//         'one_silangan_room_fan.jpg',
//     ],
//     tags: [
//         'Private dorm',
//         'Near main gate',
//         'Aircon & fan rooms',
//         'Daily rates available',
//         'Group rates available',
//     ],
//     rooms: [
//         {
//         room_number: 'AC-1',
//         room_building: 'Silangan Place',
//         room_type: 'single',
//         room_stay_type: 'non_transient',
//         room_capacity: 1,
//         room_current_occupancy: 0,
//         room_availability: 'available',
//         room_rent: 5000,
//         tenant_restriction: 'coed',
//         advance_months: 1,
//         deposit_months: 1,
//         reservation_fee_type: 'fixed',
//         reservation_fee_value: 500,
//         inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk'],
//         preferences: ['Window view'],
//         },
//         {
//         room_number: 'AC-2',
//         room_building: 'Silangan Place',
//         room_type: 'double',
//         room_stay_type: 'non_transient',
//         room_capacity: 2,
//         room_current_occupancy: 1,
//         room_availability: 'available',
//         room_rent: 3500,
//         tenant_restriction: 'non-coed',
//         advance_months: 1,
//         deposit_months: 1,
//         reservation_fee_type: 'fixed',
//         reservation_fee_value: 500,
//         inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk'],
//         },
//         {
//         room_number: 'FAN1',
//         room_building: 'Silangan Place',
//         room_type: 'single',
//         room_stay_type: 'non_transient',
//         room_capacity: 1,
//         room_current_occupancy: 0,
//         room_availability: 'available',
//         room_rent: 3500,
//         tenant_restriction: 'coed',
//         advance_months: 1,
//         deposit_months: 1,
//         reservation_fee_type: 'fixed',
//         reservation_fee_value: 500,
//         inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk'],
//         },
//         {
//         room_number: 'GRP1',
//         room_building: 'Silangan Place',
//         room_type: 'shared',
//         room_stay_type: 'transient',
//         room_capacity: 7,
//         room_current_occupancy: 0,
//         room_availability: 'available',
//         room_rent: 14000, // group rate ~₱2,000/room/day × 7 nights equiv
//         tenant_restriction: 'coed',
//         inclusions: ['Aircon', 'WiFi', 'Cabinet'],
//         },
//     ],  
// }

/*
    Dorm stuff from GMaps + Claude (ty claude)
*/
const estellar_residences: DormSeedData = {
    accommodation_name: 'Estellar Residences',
    accommodation_location:
        'Jose R. Velasco Ave., Batong Malake, Los Baños, Laguna 4031',
    latitude: 14.170100,
    longitude: 121.244800,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 60,
    walking_distance: 4,
    biking_distance: 2,
    driving_distance: 1,
    application_start_date: '2026-06-01',
    application_end_date: '2026-09-30',
    images: [
        'estellar_front.jpg',
        'estellar_room_single.jpg',
        'estellar_room_shared.jpg',
        'estellar_lobby.jpg',
    ],
    tags: [
        'Private dorm',
        'Near main gate',
        'Aircon',
        'WiFi',
        'CCTV',
        'Parking available',
    ],
    rooms: [
        {
        room_number: 'S101',
        room_building: 'Estellar Bldg',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 7500,
        tenant_restriction: 'coed',
        room_size: 14,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        preferences: ['Ground floor'],
        },
        {
        room_number: 'S102',
        room_building: 'Estellar Bldg',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 7500,
        tenant_restriction: 'coed',
        room_size: 14,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'D201',
        room_building: 'Estellar Bldg',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 5500,
        tenant_restriction: 'non-coed',
        room_size: 18,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        preferences: ['Upper floor', 'Window view'],
        },
        {
        room_number: 'D202',
        room_building: 'Estellar Bldg',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 2,
        room_availability: 'occupied',
        room_rent: 5500,
        tenant_restriction: 'non-coed',
        room_size: 18,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'SH301',
        room_building: 'Estellar Bldg',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 3800,
        tenant_restriction: 'non-coed',
        room_size: 24,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'SH302',
        room_building: 'Estellar Bldg',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3800,
        tenant_restriction: 'non-coed',
        room_size: 24,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        preferences: ['Quiet floor'],
        },
    ],
}

const zeta_dormitory: DormSeedData = {
    accommodation_name: 'Zeta Dormitory',
    accommodation_location:
        'Batong Malake, Los Baños, Laguna 4031',
    latitude: 14.170600,
    longitude: 121.245300,
    accommodation_type: 'off-campus',
    tenant_restriction: 'female-only',
    accommodation_capacity: 45,
    walking_distance: 5,
    biking_distance: 2,
    driving_distance: 2,
    images: [
        'zeta_dorm_front.jpg',
        'zeta_dorm_room.jpg',
        'zeta_dorm_common.jpg',
    ],
    tags: [
        'Private dorm',
        'Female-exclusive',
        'Transient accepted',
        '5 min to UPLB gate',
        'WiFi',
        'CCTV',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: 'Zeta Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '102',
        room_building: 'Zeta Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '103',
        room_building: 'Zeta Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 3,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        preferences: ['Ground floor', 'Quiet room'],
        },
        {
        room_number: '201',
        room_building: 'Zeta Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: 'T-01',
        room_building: 'Zeta Dorm',
        room_type: 'shared',
        room_stay_type: 'transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 4500, // transient, monthly-equivalent placeholder
        tenant_restriction: 'non-coed',
        inclusions: ['WiFi', 'Cabinet', 'Electric fan'],
        },
    ],
}

const marhaba_dormitory: DormSeedData = {
    accommodation_name: 'Marhaba Dormitory',
    accommodation_location:
        'College, Los Baños, Laguna 4031',
    latitude: 14.169400,
    longitude: 121.243900,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 50,
    walking_distance: 6,
    biking_distance: 3,
    driving_distance: 2,
    images: [
        'marhaba_front.jpg',
        'marhaba_room.jpg',
        'marhaba_common.jpg',
        'marhaba_bathroom.jpg',
    ],
    tags: [
        'Private dorm',
        'Complete facilities',
        'Aircon',
        'WiFi',
        'CCTV',
        'Laundry area',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: 'Marhaba Dorm',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 6500,
        tenant_restriction: 'coed',
        room_size: 12,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk',
        ],
        },
        {
        room_number: '102',
        room_building: 'Marhaba Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 2,
        room_availability: 'occupied',
        room_rent: 4500,
        tenant_restriction: 'non-coed',
        room_size: 16,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk',
        ],
        },
        {
        room_number: '103',
        room_building: 'Marhaba Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 3200,
        tenant_restriction: 'non-coed',
        room_size: 22,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk',
        ],
        },
        {
        room_number: '201',
        room_building: 'Marhaba Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3200,
        tenant_restriction: 'non-coed',
        room_size: 22,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk',
        ],
        preferences: ['Upper floor'],
        },
        {
        room_number: '202',
        room_building: 'Marhaba Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 5,
        room_current_occupancy: 3,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        room_size: 26,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: [
            'Electric fan', 'WiFi', 'Shared bathroom',
            'Cabinet', 'Study desk',
        ],
        },
    ],
}

const reese_dormitory: DormSeedData = {
    accommodation_name: 'R.E.E.S.E. Dormitory',
    accommodation_location:
        'Batong Malake, beside UPLB, Los Baños, Laguna 4031',
    latitude: 14.168900,
    longitude: 121.243200,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 55,
    walking_distance: 1,
    biking_distance: 1,
    driving_distance: 1,
    images: [
        'reese_dorm_front.jpg',
        'reese_dorm_room.jpg',
        'reese_dorm_outside.jpg',
    ],
    tags: [
        'Private dorm',
        'Steps from campus',
        'Est. 2014',
        'WiFi',
        'Security personnel',
        'Laundry area',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: 'REESE Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 3,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '102',
        room_building: 'REESE Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '103',
        room_building: 'REESE Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 6,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2200,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: 'REESE Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        preferences: ['Upper floor'],
        },
        {
        room_number: '202',
        room_building: 'REESE Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3200,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
    ],
}

const mix_match_dormitory: DormSeedData = {
    accommodation_name: 'Mix-Match Dormitory',
    accommodation_location:
        'College, Los Baños, Laguna 4031',
    latitude: 14.169000,
    longitude: 121.244500,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 40,
    walking_distance: 5,
    biking_distance: 2,
    driving_distance: 2,
    images: [
        'mixmatch_front.jpg',
        'mixmatch_room_single.jpg',
        'mixmatch_room_shared.jpg',
    ],
    tags: [
        'Private dorm',
        'Flexible room types',
        'WiFi',
        'CCTV',
        'Affordable rates',
    ],
    rooms: [
        {
        room_number: 'A-01',
        room_building: 'Mix-Match Dorm',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 5000,
        tenant_restriction: 'coed',
        room_size: 10,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk'],
        },
        {
        room_number: 'A-02',
        room_building: 'Mix-Match Dorm',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 4000,
        tenant_restriction: 'coed',
        room_size: 10,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk'],
        },
        {
        room_number: 'B-01',
        room_building: 'Mix-Match Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3000,
        tenant_restriction: 'non-coed',
        room_size: 15,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk'],
        preferences: ['Quiet room'],
        },
        {
        room_number: 'C-01',
        room_building: 'Mix-Match Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2500,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk'],
        },
        {
        room_number: 'C-02',
        room_building: 'Mix-Match Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 6,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2200,
        tenant_restriction: 'non-coed',
        room_size: 28,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk'],
        },
    ],
}

const riela_dormitory: DormSeedData = {
    accommodation_name: 'Riela Dormitory',
    accommodation_location:
        'College, Los Baños, Laguna 4031',
    latitude: 14.168500,
    longitude: 121.242800,
    accommodation_type: 'off-campus',
    tenant_restriction: 'female-only',
    accommodation_capacity: 35,
    walking_distance: 7,
    biking_distance: 3,
    driving_distance: 2,
    images: [
        'riela_front.jpg',
        'riela_room.jpg',
        'riela_common_area.jpg',
    ],
    tags: [
        'Private dorm',
        'Female-exclusive',
        'WiFi',
        'CCTV',
        'Laundry area',
        'Near UPLB',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: 'Riela Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '102',
        room_building: 'Riela Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: 'Riela Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 3,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Aircon'],
        preferences: ['Upper floor', 'Aircon room'],
        },
        {
        room_number: '202',
        room_building: 'Riela Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3500,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Aircon'],
        },
    ],
}

const bay_anne_dormitory: DormSeedData = {
    accommodation_name: 'Bay-Anne Dormitory',
    accommodation_location:
        'Anos, Los Baños, Laguna 4031',
    latitude: 14.167200,
    longitude: 121.241600,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 40,
    walking_distance: 10,
    biking_distance: 4,
    driving_distance: 3,
    images: [
        'bay_anne_front.jpg',
        'bay_anne_room.jpg',
        'bay_anne_outside.jpg',
    ],
    tags: [
        'Private dorm',
        'Coed',
        'WiFi',
        'CCTV',
        'Affordable rates',
        'Near UPLB',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: 'Bay-Anne Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2300,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '102',
        room_building: 'Bay-Anne Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 3,
        room_availability: 'available',
        room_rent: 2300,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '103',
        room_building: 'Bay-Anne Dorm',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 6,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: 'Bay-Anne Dorm',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 3000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Aircon'],
        },
        {
        room_number: 'T-01',
        room_building: 'Bay-Anne Dorm',
        room_type: 'shared',
        room_stay_type: 'transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3600,
        tenant_restriction: 'coed',
        inclusions: ['WiFi', 'Cabinet', 'Electric fan'],
        },
    ],
}

const rigors_dormitory: DormSeedData = {
    accommodation_name: "Rigor's Dormitory",
    accommodation_location:
        'College, Los Baños, Laguna 4031',
    latitude: 14.168000,
    longitude: 121.242200,
    accommodation_type: 'off-campus',
    tenant_restriction: 'male-only',
    accommodation_capacity: 30,
    walking_distance: 8,
    biking_distance: 3,
    driving_distance: 2,
    images: [
        'rigors_front.jpg',
        'rigors_room.jpg',
        'rigors_outside.jpg',
    ],
    tags: [
        'Private dorm',
        'Male-exclusive',
        'WiFi',
        'CCTV',
        'Near UPLB',
        'Affordable',
    ],
    rooms: [
        {
        room_number: '101',
        room_building: "Rigor's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2400,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '102',
        room_building: "Rigor's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2400,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '201',
        room_building: "Rigor's Dorm",
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 4,
        room_availability: 'occupied',
        room_rent: 2400,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Electric fan'],
        },
        {
        room_number: '202',
        room_building: "Rigor's Dorm",
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 3000,
        tenant_restriction: 'non-coed',
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['WiFi', 'Cabinet', 'Study desk', 'Aircon'],
        preferences: ['Upper floor', 'Quiet room'],
        },
    ],
}

const koru_residences: DormSeedData = {
    accommodation_name: 'Koru Residences',
    accommodation_location:
        '10051-B Grove, Lopez Ave., Los Baños, Laguna 4030',
    latitude: 14.168300,
    longitude: 121.239800,
    accommodation_type: 'off-campus',
    tenant_restriction: 'female-only',
    accommodation_capacity: 30,
    walking_distance: 10,
    biking_distance: 4,
    driving_distance: 3,
    application_start_date: '2026-06-01',
    application_end_date: '2026-09-30',
    images: [
        'koru_front.jpg',
        'koru_room_single.jpg',
        'koru_room_double.jpg',
        'koru_lounge.jpg',
    ],
    tags: [
        'Private dorm',
        'Female-exclusive',
        'Boutique dormitel',
        'Aircon',
        'En-suite bathroom',
        'WiFi',
        'High-end amenities',
    ],
    rooms: [
        {
        room_number: 'K-101',
        room_building: 'Koru Bldg',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 9000,
        tenant_restriction: 'non-coed',
        room_size: 16,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1500,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Hot shower', 'Cabinet', 'Study desk',
            'Bed with mattress', 'Curtains',
        ],
        preferences: ['Ground floor', 'Garden view'],
        },
        {
        room_number: 'K-102',
        room_building: 'Koru Bldg',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 9000,
        tenant_restriction: 'non-coed',
        room_size: 16,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1500,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Hot shower', 'Cabinet', 'Study desk',
            'Bed with mattress', 'Curtains',
        ],
        },
        {
        room_number: 'K-201',
        room_building: 'Koru Bldg',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 6500,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1500,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Hot shower', 'Cabinet', 'Study desk',
            'Bed with mattress', 'Curtains',
        ],
        preferences: ['Upper floor', 'Window view'],
        },
        {
        room_number: 'K-202',
        room_building: 'Koru Bldg',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 2,
        room_availability: 'occupied',
        room_rent: 6500,
        tenant_restriction: 'non-coed',
        room_size: 20,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1500,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Hot shower', 'Cabinet', 'Study desk',
            'Bed with mattress', 'Curtains',
        ],
        },
        {
        room_number: 'K-301',
        room_building: 'Koru Bldg',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 3,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 5000,
        tenant_restriction: 'non-coed',
        room_size: 24,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'Shared bathroom',
            'Hot shower', 'Cabinet', 'Study desk',
            'Bed with mattress',
        ],
        },
    ],
}

const westbrook_residences: DormSeedData = {
    accommodation_name: 'Westbrook Residences',
    accommodation_location:
        '10961 Jose R. Velasco Ave., College, Los Baños, Laguna 4031',
    latitude: 14.169700,
    longitude: 121.243500,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 50,
    walking_distance: 3,
    biking_distance: 1,
    driving_distance: 1,
    images: [
        'westbrook_front.jpg',
        'westbrook_room.jpg',
        'westbrook_common.jpg',
        'westbrook_exterior.jpg',
    ],
    tags: [
        'Private dorm',
        'Transient accepted',
        'Steps from main library',
        'Aircon',
        'WiFi',
        'Parking',
        'CCTV',
    ],
    rooms: [
        {
        room_number: 'W-101',
        room_building: 'Westbrook',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 7000,
        tenant_restriction: 'coed',
        room_size: 14,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'W-102',
        room_building: 'Westbrook',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 7000,
        tenant_restriction: 'coed',
        room_size: 14,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'W-201',
        room_building: 'Westbrook',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 5000,
        tenant_restriction: 'non-coed',
        room_size: 18,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'W-202',
        room_building: 'Westbrook',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 2,
        room_availability: 'occupied',
        room_rent: 5000,
        tenant_restriction: 'non-coed',
        room_size: 18,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 1000,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Study desk', 'Bed with mattress',
        ],
        },
        {
        room_number: 'W-T01',
        room_building: 'Westbrook',
        room_type: 'single',
        room_stay_type: 'transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 30000, // ₱1,000/day × 30 days equivalent
        tenant_restriction: 'coed',
        room_size: 14,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Bed with mattress',
        ],
        },
        {
        room_number: 'W-T02',
        room_building: 'Westbrook',
        room_type: 'double',
        room_stay_type: 'transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 30000,
        tenant_restriction: 'coed',
        room_size: 18,
        inclusions: [
            'Aircon', 'WiFi', 'En-suite bathroom',
            'Cabinet', 'Bed with mattress',
        ],
        },
    ],
}

const holland_tulips: DormSeedData = {
    accommodation_name: 'Holland Tulips Dormitory',
    accommodation_location:
        'Jose R. Velasco Ave., College, Los Baños, Laguna 4031',
    latitude: 14.169950,
    longitude: 121.241800,
    accommodation_type: 'off-campus',
    tenant_restriction: 'coed',
    accommodation_capacity: 40,
    walking_distance: 4,
    biking_distance: 2,
    driving_distance: 1,
    images: [
        'holland_tulips_front.jpg',
        'holland_tulips_room.jpg',
        'holland_tulips_outside.jpg',
    ],
    tags: [
        'Private dorm',
        'Near Velasco Ave.',
        'WiFi',
        'CCTV',
        'Aircon rooms available',
        'Near UPLB main library',
    ],
    rooms: [
        {
        room_number: 'HT-101',
        room_building: 'Holland Tulips',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 1,
        room_availability: 'occupied',
        room_rent: 6000,
        tenant_restriction: 'coed',
        room_size: 12,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        },
        {
        room_number: 'HT-102',
        room_building: 'Holland Tulips',
        room_type: 'single',
        room_stay_type: 'non_transient',
        room_capacity: 1,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 6000,
        tenant_restriction: 'coed',
        room_size: 12,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        preferences: ['Quiet room'],
        },
        {
        room_number: 'HT-201',
        room_building: 'Holland Tulips',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 4200,
        tenant_restriction: 'non-coed',
        room_size: 16,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        },
        {
        room_number: 'HT-202',
        room_building: 'Holland Tulips',
        room_type: 'double',
        room_stay_type: 'non_transient',
        room_capacity: 2,
        room_current_occupancy: 1,
        room_availability: 'available',
        room_rent: 4200,
        tenant_restriction: 'non-coed',
        room_size: 16,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 800,
        inclusions: ['Aircon', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        },
        {
        room_number: 'HT-301',
        room_building: 'Holland Tulips',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 0,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        room_size: 22,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        },
        {
        room_number: 'HT-302',
        room_building: 'Holland Tulips',
        room_type: 'shared',
        room_stay_type: 'non_transient',
        room_capacity: 4,
        room_current_occupancy: 2,
        room_availability: 'available',
        room_rent: 2800,
        tenant_restriction: 'non-coed',
        room_size: 22,
        advance_months: 1,
        deposit_months: 1,
        reservation_fee_type: 'fixed',
        reservation_fee_value: 500,
        inclusions: ['Electric fan', 'WiFi', 'Cabinet', 'Study desk', 'Shared bathroom'],
        },
    ],
}

export const PRIVATE_DORMS: DormSeedData[] = [
    scholars_dormitory,
    ccp_hostel,
    arable_premier_residences,
    //one_silangan,
    estellar_residences,
    zeta_dormitory,
    marhaba_dormitory,
    reese_dormitory,
    mix_match_dormitory,
    riela_dormitory,
    bay_anne_dormitory,
    rigors_dormitory,
    koru_residences,
    westbrook_residences,
    holland_tulips
]