import { useState, useMemo } from "react"

import Sidebar from "../../components/Sidebar"
import HeroBanner from "../../components/dashboard/HeroBanner"
import Card from "../../components/ui/Card"
import StatBar from "../../components/ui/StatBar"
import DonutStatCard from "../../components/dashboard/DonutStatCard"
import Button from "../../components/Button"
import StatusBadge from "../../components/ui/StatusBadge"

//Interfaces
interface ManagerProfile {
    fullName: string
    shortName: string
    email: string
    phoneNumber: string
    status: string
    dormitory: string
}

interface HeroContent {
    greeting: string
    title: string
    subtitle: string
}

interface Student {
  fullName: string
  shortName: string
  course: string
  campus: string
  email: string
  phone: string
  studentNo: string
  college: string
  yearLevel: string
  status: string
}

interface Accomodation {
    building: string
}

interface Application {
    student: Student
    accommodation: Accomodation
    roomType: "single" | "double" | "shared"
    stayType: "transient" | "non-transient"
    rejectionReason?: string | null
    applicationStatus: 'pending' | 'approved' | 'rejected' | 'cancelled' | 'waitlisted' | 'under_review'
    durationOfStayDays: number
    applicationDate: string 
}

//update na lang para sa Room model
interface Assignment {
    student: Application
    roomNumber: string
    roomBuilding: string
    roomType: string
    stayType: string
    moveIn: string
    expectedMoveOut: string
    status: "assigned" | "not assigned"
}

//Mock data
const managerProfile: ManagerProfile = {
    fullName: "Dal Cadsawan",
    shortName: "Dal",
    email: "ddcadsawan@up.edu.ph",
    phoneNumber: "+63 912 345 6789",
    status: "Active",
    dormitory: "Narra Residences"
}

const heroContent: HeroContent = {
    greeting: "Good Day",
    title: "Assign a room to your confirmed applicant",
    subtitle: "We make it easy for you to track the accommodation applications you manage. "
}

//Stuff generated by Claude (thanks Claude)
const students: Student[] = [
  {
    fullName: "Ana Marie Reyes",
    shortName: "Ana Reyes",
    course: "BS Computer Science",
    campus: "Main Campus",
    email: "anamariel.reyes@student.edu.ph",
    phone: "09171234567",
    studentNo: "2021-00123",
    college: "College of Engineering",
    yearLevel: "3rd Year",
    status: "Regular"
  },
  {
    fullName: "Carlos Miguel Santos",
    shortName: "Carlos Santos",
    course: "BS Civil Engineering",
    campus: "Main Campus",
    email: "carlos.santos@student.edu.ph",
    phone: "09189876543",
    studentNo: "2020-00456",
    college: "College of Engineering",
    yearLevel: "4th Year",
    status: "Regular"
  },
  {
    fullName: "Maria Cristina Dela Cruz",
    shortName: "Maria Dela Cruz",
    course: "BS Nursing",
    campus: "North Campus",
    email: "mariacristina.delacruz@student.edu.ph",
    phone: "09201122334",
    studentNo: "2022-00789",
    college: "College of Allied Health",
    yearLevel: "2nd Year",
    status: "Regular"
  },
  {
    fullName: "Jose Ramon Villanueva",
    shortName: "Jose Villanueva",
    course: "BS Architecture",
    campus: "Main Campus",
    email: "jose.villanueva@student.edu.ph",
    phone: "09334455667",
    studentNo: "2019-01011",
    college: "College of Architecture",
    yearLevel: "5th Year",
    status: "Irregular"
  },
  {
    fullName: "Liza Mae Fontanilla",
    shortName: "Liza Fontanilla",
    course: "BS Education",
    campus: "South Campus",
    email: "lizamae.fontanilla@student.edu.ph",
    phone: "09451234567",
    studentNo: "2023-00321",
    college: "College of Education",
    yearLevel: "1st Year",
    status: "Regular"
  },
  {
    fullName: "Ramon Kristoffer Aquino",
    shortName: "Ramon Aquino",
    course: "BS Information Technology",
    campus: "Main Campus",
    email: "ramon.aquino@student.edu.ph",
    phone: "09278765432",
    studentNo: "2022-00654",
    college: "College of Engineering",
    yearLevel: "2nd Year",
    status: "Regular"
  }
]

const accommodations: Accomodation[] = [
  { building: "Building 6" },
  { building: "Building 3" },
  { building: "Building 1" },
  { building: "Building 4" },
  { building: "Building 2" },
  { building: "Building 5" }  
]

const applications: Application[] = [
  {
    student: students[0],
    accommodation: accommodations[0],
    roomType: "single",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 180,
    applicationDate: "Mar 12, 2026"
  },
  {
    student: students[1],
    accommodation: accommodations[1],
    roomType: "double",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 180,
    applicationDate: "Mar 14, 2026"
  },
  {
    student: students[2],
    accommodation: accommodations[2],
    roomType: "shared",
    stayType: "transient",
    rejectionReason: null,
    applicationStatus: "under_review",
    durationOfStayDays: 7,
    applicationDate: "Mar 15, 2026"
  },
  {
    student: students[3],
    accommodation: accommodations[3],
    roomType: "single",
    stayType: "non-transient",
    rejectionReason: "No available slots for the selected room type.",
    applicationStatus: "rejected",
    durationOfStayDays: 180,
    applicationDate: "Mar 16, 2026"
  },
  {
    student: students[4],
    accommodation: accommodations[4],
    roomType: "double",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "waitlisted",
    durationOfStayDays: 180,
    applicationDate: "Mar 17, 2026"
  },
  {
    student: students[5],
    accommodation: accommodations[5],
    roomType: "shared",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "waitlisted",
    durationOfStayDays: 180,
    applicationDate: "Mar 18, 2026"
  },
  {
    student: students[0],
    accommodation: accommodations[2],
    roomType: "double",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 180,
    applicationDate: "Mar 19, 2026"
  },
  {
    student: students[2],
    accommodation: accommodations[3],
    roomType: "single",
    stayType: "transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 14,
    applicationDate: "Mar 20, 2026"
  },
  {
    student: students[4],
    accommodation: accommodations[0],
    roomType: "shared",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 180,
    applicationDate: "Mar 21, 2026"
  },
  {
    student: students[5],
    accommodation: accommodations[1],
    roomType: "single",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 180,
    applicationDate: "Mar 22, 2026"
  },
  {
    student: students[3],
    accommodation: accommodations[5],
    roomType: "double",
    stayType: "transient",
    rejectionReason: null,
    applicationStatus: "pending",
    durationOfStayDays: 7,
    applicationDate: "Mar 23, 2026"
  },
  {
    student: students[2],
    accommodation: accommodations[2],
    roomType: "shared",
    stayType: "transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 7,
    applicationDate: "Mar 20, 2026"
  },  // index [11]
  {
    student: students[3],
    accommodation: accommodations[3],
    roomType: "single",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 180,
    applicationDate: "Mar 21, 2026"
  },  // index [12]
  {
    student: students[4],
    accommodation: accommodations[4],
    roomType: "double",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 180,
    applicationDate: "Mar 22, 2026"
  },  // index [13]
  {
    student: students[0],
    accommodation: accommodations[5],
    roomType: "shared",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 180,
    applicationDate: "Mar 23, 2026"
  },  // index [14]
  {
    student: students[5],
    accommodation: accommodations[0],
    roomType: "single",
    stayType: "non-transient",
    rejectionReason: null,
    applicationStatus: "approved",
    durationOfStayDays: 180,
    applicationDate: "Mar 24, 2026"
  },  // index [15]
]


const assignments: Assignment[] = [
  {
    student: applications[1],   // Carlos Miguel Santos — already existed
    roomNumber: "312",
    roomBuilding: "Building 4",
    roomType: "Double",
    stayType: "Non-Transient",
    moveIn: "Mar 15, 2026",
    expectedMoveOut: "Aug 15, 2026",
    status: "assigned"
  },
  {
    student: applications[11],  // Maria Cristina Dela Cruz
    roomNumber: "204",
    roomBuilding: "Building 1",
    roomType: "Shared",
    stayType: "Transient",
    moveIn: "Mar 21, 2026",
    expectedMoveOut: "Mar 28, 2026",
    status: "assigned"
  },
  {
    student: applications[12],  // Jose Ramon Villanueva
    roomNumber: "105",
    roomBuilding: "Building 4",
    roomType: "Single",
    stayType: "Non-Transient",
    moveIn: "",
    expectedMoveOut: "",
    status: "not assigned"
  },
  {
    student: applications[13],  // Liza Mae Fontanilla
    roomNumber: "308",
    roomBuilding: "Building 2",
    roomType: "Double",
    stayType: "Non-Transient",
    moveIn: "Mar 23, 2026",
    expectedMoveOut: "Aug 23, 2026",
    status: "assigned"
  },
  {
    student: applications[14],  // Ana Marie Reyes
    roomNumber: "",
    roomBuilding: "",
    roomType: "Shared",
    stayType: "Non-Transient",
    moveIn: "",
    expectedMoveOut: "",
    status: "not assigned"
  },
  {
    student: applications[15],  // Ramon Kristoffer Aquino
    roomNumber: "410",
    roomBuilding: "Building 5",
    roomType: "Single",
    stayType: "Non-Transient",
    moveIn: "Mar 25, 2026",
    expectedMoveOut: "Aug 25, 2026",
    status: "assigned"
  },
]

const ASSIGNMENTS_PER_PAGE = 5
const SORT_OPTS = ["Name", "Status", "Date", "Room Type"]

export default function RoomAssignment() {
    const [currentPage, setCurrentPage] = useState(1)
    const [selectedAssignment, setSelectedAssignment] = useState<Assignment | null>(null)
    const [modalAssignment, setModalAssignment] = useState<Assignment | null>(null)

    const [sortBy, setSortBy] = useState("Status")
    const [sortOpen, setSortOpen] = useState(false)
    const [search, setSearch] = useState("")

    const filtered = useMemo(() => {
        const q = search.toLowerCase()
        return assignments.filter(a =>
            a.student.student.fullName.toLowerCase().includes(q) ||
            a.roomType.toLowerCase().includes(q) ||
            a.stayType.toLowerCase().includes(q) ||
            a.roomNumber.toLowerCase().includes(q) ||
            a.roomBuilding.toLowerCase().includes(q)
        )
    }, [search])


    const sortedAssignments = useMemo(() => {
        return [...filtered].sort((a, b) => {
            if (sortBy === "Status") {
                if (a.status === "not assigned" && b.status === "assigned") return -1
                if (a.status === "assigned" && b.status === "not assigned") return 1
                return 0
            }
            if (sortBy === "Name")      return a.student.student.fullName.localeCompare(b.student.student.fullName)
            if (sortBy === "Date")      return new Date(a.student.applicationDate).getTime() - new Date(b.student.applicationDate).getTime()
            if (sortBy === "Room Type") return a.roomType.localeCompare(b.roomType)
            return 0
        })
    }, [filtered, sortBy])

    const totalPages = Math.ceil(sortedAssignments.length / ASSIGNMENTS_PER_PAGE)
    const startIndex = (currentPage - 1) * ASSIGNMENTS_PER_PAGE
    const paginatedAssignments = sortedAssignments.slice(startIndex, startIndex + ASSIGNMENTS_PER_PAGE)

    //avatar initials from name
    const getInitials = (name: string) =>
        name[0]

    const openModal = (assignment: Assignment) => {
        setModalAssignment(assignment)
        setModalAssignment(assignment)
    }

    const closeModal = () => {
        setSelectedAssignment(null)
    }

    const handleSort = (option: string) => {
        setSortBy(option)
        setSortOpen(false)
        setCurrentPage(1)
    }

    const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
        setSearch(e.target.value)
        setCurrentPage(1)
    }

    const timeAgo = (dateStr: string): string => {
        const date = new Date(dateStr)
        const now = new Date()
        const seconds = Math.floor((now.getTime() - date.getTime()) / 1000)

        const intervals = [
            { label: "year",   seconds: 31536000 },
            { label: "month",  seconds: 2592000  },
            { label: "week",   seconds: 604800   },
            { label: "day",    seconds: 86400    },
            { label: "hour",   seconds: 3600     },
            { label: "minute", seconds: 60       },
        ]

        for (const interval of intervals) {
            const count = Math.floor(seconds / interval.seconds)
            if (count >= 1) return `${count} ${interval.label}${count !== 1 ? "s" : ""} ago`
        }

        return "Just now"
    }

    return (
        <div className="flex h-screen overflow-hidden bg-[#F5EEF0] font-sans">
            <Sidebar role="manager" profile={managerProfile}/>

             <div className="flex-1 flex flex-col px-8 py-5 overflow-y-auto">
                <div className="pl-10 lg:pl-0 flex flex-row border-b border-[#6B0F2B]/7 mb-2 pb-1">
                    <div className="hidden lg:inline w-2 h-8 rounded-xl mt-1 mr-2"
                        style={{ background: "linear-gradient(to bottom right, #6B0F2B 0%, #9E2040 100%)"}}
                    />
                    <h1 className="text-4xl font-serif italic font-bold text-[#6B0F2B]">
                        Room Assignment
                    </h1>
                </div>

                <main className="flex-1 flex flex-col gap-3.5 overflow-hidden">
                    <HeroBanner 
                        greeting={heroContent.greeting}
                        name={managerProfile.fullName}
                        title={heroContent.title}
                        subtitle={heroContent.subtitle}
                        type="mini"
                    />

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                        <Card 
                            className="col-span-1"
                            children={
                                <div className="flex flex-col gap-4">
                                    <StatBar
                                        label="Assigned"
                                        value={1}
                                        total={6}
                                        from="#1A7A4A"
                                        to="#2D9A5F"
                                        bg="#F0F7F3"
                                        textColor="#1A7A4A"
                                    />

                                    <hr className="border border-[#F5EEF0] my-1" />

                                    <StatBar
                                        label="Pending"
                                        value={2}
                                        total={6}
                                        from="#C9973A"
                                        to="#E0B040"
                                        bg="#FDF6E8"
                                        textColor="#C9973A"
                                    />
                                </div>
                            }
                        />
                        <DonutStatCard 
                            id="available-rooms"
                            title="Available Rooms"
                            titleClassName="text-[#1A7A4A] text-lg font-semibold uppercase"
                            value={100}
                            pctSize="xl"
                            total={120}
                            subtitle="of 120 total"
                            subtitleClassName="text-lg"
                            color={["#1B7C4B", "#2C995E"]}
                            trackColor="#DCEBE3"
                            donutSize={120}
                            strokeWidth={13}
                            valueSize="3xl"
                            valueWeight="extrabold"
                        />
                        <DonutStatCard 
                            id="occupied-rooms"
                            title="Occupied Rooms"
                            titleClassName="text-[#6B0F2B] text-lg font-semibold uppercase"
                            value={20}
                            pctSize="xl"
                            total={120}
                            subtitle="of 120 total"
                            subtitleClassName="text-lg"
                            color={["#72112D", "#921C3A"]}
                            trackColor="#F1E0E6"
                            donutSize={120}
                            strokeWidth={13}
                            valueSize="3xl"
                            valueWeight="extrabold"
                        />
                    </div>

                    <Card
                        children={
                            <div className="">
                                <div className="flex items-center justify-between mb-2 gap-3 flex-wrap border-b border-[#F5ECF0] pb-2">
                                    <h2 className="text-[#1A0008] font-bold text-base lg:text-lg">
                                        Room Assignment
                                    </h2>
                                    <div className="flex items-center gap-2 ml-auto">
                                        {/* Sort dropdown */}
                                        <div className="relative">
                                            <button
                                                onClick={() => setSortOpen(o => !o)}
                                                className="flex items-center gap-2 border border-[#E8D5DC] rounded-xl px-3 py-2 text-sm bg-white hover:bg-[#F5ECF0] transition min-w-[140px]"
                                            >
                                                <span className="flex flex-col text-left">
                                                    <span className="text-[9px] uppercase text-[#9A7080] font-bold leading-none">Sort By</span>
                                                    <span className="text-[#1A0008] font-medium text-sm">{sortBy}</span>
                                                </span>
                                                <svg className="ml-auto w-4 h-4 text-[#9A7080]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                                                </svg>
                                            </button>
                                            {sortOpen && (
                                                <div className="absolute z-10 top-full mt-1 right-0 bg-white border border-[#E8D5DC] rounded-xl shadow-md overflow-hidden w-full">
                                                    {SORT_OPTS.map(opt => (
                                                        <button
                                                            key={opt}
                                                            onClick={() => handleSort(opt)}
                                                            className={`w-full text-left px-4 py-2 text-sm hover:bg-[#F5ECF0] transition
                                                                ${sortBy === opt ? "text-[#6B0F2B] font-semibold" : "text-[#1A0008]"}`}
                                                        >
                                                            {opt}
                                                        </button>
                                                    ))}
                                                </div>
                                            )}
                                        </div>

                                        {/* Search */}
                                        <div className="flex items-center gap-2 border border-[#E8D5DC] rounded-xl px-3 py-2 bg-white">
                                            <svg className="w-4 h-4 text-[#9A7080] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-4.35-4.35M17 11A6 6 0 1 1 5 11a6 6 0 0 1 12 0z" />
                                            </svg>
                                            <input
                                                type="text"
                                                placeholder="Search applications..."
                                                value={search}
                                                onChange={handleSearch}
                                                className="text-sm outline-none bg-transparent text-[#1A0008] placeholder-[#C4A4B0] w-36"
                                            />
                                        </div>
                                    </div>
                                </div>
                                <div className="grid grid-cols-4 lg:grid-cols-5 border-b border-[#F5ECF0] uppercase"
                                    style={{ gridTemplateColumns: "2fr 1.5fr 1fr 1.5fr 1.5fr" }}
                                >
                                    <p className="col-span-1 text-[#9A7080] text-xs lg:text-md font-bold p-1">
                                        Student
                                    </p>
                                    <p className="col-span-1 text-[#9A7080] text-xs lg:text-md font-bold p-1">
                                        Confirmed Room Type
                                    </p>
                                    <p className="col-span-1 text-[#9A7080] text-xs lg:text-md font-bold p-1">
                                        Date Confirmed
                                    </p>
                                    <p className="hidden lg:block col-span-1 text-center text-[#9A7080] text-xs lg:text-md font-bold p-1">
                                        Status
                                    </p>
                                    <p className="col-span-1 text-center text-[#9A7080] text-xs lg:text-md font-bold p-1">
                                        Action
                                    </p>
                                </div>
                                {sortedAssignments.length > 0 
                                    ? (
                                        <>
                                        <div className="flex flex-col">
                                            {paginatedAssignments.map((assignment, i) => {
                                                return(
                                                    <div key={i} className={`grid grid-cols-4 lg:grid-cols-5 flex justify-between items-center py-2.5 pl-1
                                                        ${assignment.status === "assigned" ? "bg-[#1A7A4A]/5" : ""}
                                                        
                                                    `} style={{ gridTemplateColumns: "2fr 1.5fr 1fr 1.5fr 1.5fr" }}
                                                    >
                                                        <div className="col-span-1 flex items-center gap-2">
                                                            <div className="hidden lg:flex w-9 h-9 rounded-xl flex-shrink-0 items-center justify-center text-white text-xs font-bold"
                                                                style={{ background: "linear-gradient(135deg, #6B0F2B, #9E2040)" }}>
                                                                {getInitials(assignment.student.student.fullName)}
                                                            </div>
                                                            <p className="font-bold text-[12px] ml-1 lg:ml-0 lg:text-sm text-[#1A0008]">{assignment.student.student.fullName}</p>
                                                        </div>

                                                        <div className="col-span-1 flex flex-col justfify-center">
                                                            <p className="text-sm text-[#1A0008] capitalize">
                                                                {assignment.stayType}
                                                            </p>
                                                            <p className="text-xs text-[#C8B0B8]">
                                                                {assignment.roomType}
                                                            </p>
                                                        </div>

                                                        <div className="col-span-1 flex flex-col">
                                                            {/* NOTE FOR BACKEND: This should be dateConfirmed */}
                                                            <p className={`text-sm
                                                                    ${assignment.status === "assigned" ? "text-[#1A0008]" : "text-[#C8B0B8]"}
                                                                `}>
                                                                {assignment.status === "assigned" ? assignment.student.applicationDate : "—"}
                                                            </p>
                                                            <p className="text-sm text-[#C8B0B8]">
                                                                {assignment.status === "assigned" ? timeAgo(assignment.student.applicationDate) : "Not yet assigned"}
                                                            </p>
                                                        </div>
                                                        <div className="col-span-1 px-2 flex justify-center items-center">
                                                            <span className={`inline-flex items-center justify-center gap-1 text-xs px-2 py-1.5 w-32 rounded-full font-bold capitalize
                                                                ${assignment.status === "not assigned" 
                                                                    ? "bg-[#9E2040]/10 text-[#9E2040]" 
                                                                    : "bg-[#1A7A4A]/10 text-[#1A7A4A]"}`}>
                                                                <span className={`w-2 h-2 flex-shrink-0 rounded-full 
                                                                    ${assignment.status === "not assigned" ? "bg-[#9E2040]" : "bg-[#1A7A4A]"}`} 
                                                                />
                                                                {assignment.status === "not assigned" ? "Not Assigned" : "Assigned"}
                                                            </span>
                                                        </div>
                                                        <div className="col-span-1 flex justify-center">
                                                            <Button 
                                                                variant="reddishPink" 
                                                                size="sm" 
                                                                className="w-28 justify-center"
                                                                onClick={() => openModal(assignment)}
                                                            >
                                                                {assignment.status === "assigned" ? "View" : "Assign Room"}
                                                            </Button>
                                                        </div>
                                                    </div>
                                                )    
                                            })}
                                        </div>
                                        <div className="flex items-center justify-between mt-3">
                                            <p className="text-xs text-[#9A7080]">
                                                Showing {startIndex + 1}–{Math.min(startIndex + ASSIGNMENTS_PER_PAGE, sortedAssignments.length)} of {sortedAssignments.length} records
                                            </p>
                                            <div className="flex items-center justify-center gap-1">
                                                {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
                                                    <button
                                                        key={page}
                                                        onClick={() => setCurrentPage(page)}
                                                        className={`w-7 h-7 text-xs rounded-md font-medium transition flex items-center justify-center
                                                            ${currentPage === page
                                                                ? "text-white"
                                                                : "text-[#9A7080] border border-[#E8D5DC] hover:bg-[#F5ECF0]"
                                                            }`}
                                                        style={currentPage === page ? { background: "linear-gradient(135deg, #6B0F2B, #9E2040)" } : {}}
                                                    >
                                                        {page}
                                                    </button>
                                                ))}
                                                {currentPage < totalPages && (
                                                    <button
                                                        onClick={() => setCurrentPage(p => p + 1)}
                                                        className="flex items-center justify-center w-7 h-7 text-xs rounded-md border border-[#E8D5DC] text-[#9A7080] hover:bg-[#F5ECF0] transition"
                                                    >
                                                        {">"}
                                                    </button>
                                                )}
                                            </div>
                                        </div>
                                        </>
                                    )
                                    : (
                                        <p className="text-sm text-[#9A7080] py-6 text-center">
                                            {search ? "No applications match your search." : "No assignments found."}
                                        </p>
                                    )
                                }
                            </div>
                        }
                    />
                </main>
            </div>
        </div>
    )
}