/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccommodationSchema extends BaseModel {
  static $columns = ['accommodationCapacity', 'accommodationLocation', 'accommodationName', 'accommodationType', 'applicationEndDate', 'applicationStartDate', 'bikingDistance', 'businessPermitId', 'drivingDistance', 'id', 'invitedManagerEmail', 'landlordId', 'latitude', 'longitude', 'managerId', 'primaryImageIndex', 'status', 'tenantRestriction', 'walkingDistance'] as const
  $columns = AccommodationSchema.$columns
  @column()
  declare accommodationCapacity: number
  @column()
  declare accommodationLocation: string
  @column()
  declare accommodationName: string
  @column()
  declare accommodationType: string
  @column.date()
  declare applicationEndDate: DateTime | null
  @column.date()
  declare applicationStartDate: DateTime | null
  @column()
  declare bikingDistance: number | null
  @column()
  declare businessPermitId: number
  @column()
  declare drivingDistance: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedManagerEmail: string | null
  @column()
  declare landlordId: number
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare managerId: number | null
  @column()
  declare primaryImageIndex: number | null
  @column()
  declare status: string | null
  @column()
  declare tenantRestriction: string
  @column()
  declare walkingDistance: number | null
}

export class AccommodationImageSchema extends BaseModel {
  static $columns = ['accommodationId', 'id', 'imageFileId'] as const
  $columns = AccommodationImageSchema.$columns
  @column()
  declare accommodationId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageFileId: number
}

export class AccommodationTagSchema extends BaseModel {
  static $columns = ['accommodationId', 'id', 'tagDetail'] as const
  $columns = AccommodationTagSchema.$columns
  @column()
  declare accommodationId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagDetail: string
}

export class ApplicationSchema extends BaseModel {
  static $columns = ['accommodationId', 'applicationDate', 'applicationRoomType', 'applicationStatus', 'applicationStayType', 'durationOfStayDays', 'id', 'studentNumber'] as const
  $columns = ApplicationSchema.$columns
  @column()
  declare accommodationId: number
  @column.dateTime()
  declare applicationDate: DateTime | null
  @column()
  declare applicationRoomType: string
  @column()
  declare applicationStatus: string
  @column()
  declare applicationStayType: string
  @column()
  declare durationOfStayDays: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare studentNumber: string
}

export class AssignmentSchema extends BaseModel {
  static $columns = ['actualMoveOut', 'expectedMoveOut', 'gracePeriodDays', 'id', 'moveIn', 'roomId', 'studentNumber'] as const
  $columns = AssignmentSchema.$columns
  @column.date()
  declare actualMoveOut: DateTime | null
  @column.date()
  declare expectedMoveOut: DateTime
  @column()
  declare gracePeriodDays: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare moveIn: DateTime
  @column()
  declare roomId: number
  @column()
  declare studentNumber: string
}

export class BookmarkSchema extends BaseModel {
  static $columns = ['accommodationId', 'id', 'studentNumber'] as const
  $columns = BookmarkSchema.$columns
  @column()
  declare accommodationId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare studentNumber: string
}

export class DocumentSchema extends BaseModel {
  static $columns = ['fileId', 'id', 'uploadTimestamp', 'userId'] as const
  $columns = DocumentSchema.$columns
  @column()
  declare fileId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare uploadTimestamp: DateTime | null
  @column()
  declare userId: number
}

export class FeeSchema extends BaseModel {
  static $columns = ['dueDate', 'feeAmount', 'feeBalance', 'feeCategory', 'feeStatus', 'id', 'landlordId', 'studentNumber'] as const
  $columns = FeeSchema.$columns
  @column.date()
  declare dueDate: DateTime
  @column()
  declare feeAmount: string
  @column()
  declare feeBalance: string
  @column()
  declare feeCategory: string
  @column()
  declare feeStatus: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare landlordId: number
  @column()
  declare studentNumber: string
}

export class FileMetadatumSchema extends BaseModel {
  static $columns = ['fileName', 'filePath', 'fileType', 'id'] as const
  $columns = FileMetadatumSchema.$columns
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileType: string
  @column({ isPrimary: true })
  declare id: number
}

export class LandlordSchema extends BaseModel {
  static $columns = ['tin', 'userId'] as const
  $columns = LandlordSchema.$columns
  @column()
  declare tin: string
  @column({ isPrimary: true })
  declare userId: number
}

export class LogSchema extends BaseModel {
  static $columns = ['activityDetails', 'activityType', 'actorId', 'entityId', 'entityType', 'id', 'logTimestamp'] as const
  $columns = LogSchema.$columns
  @column()
  declare activityDetails: string | null
  @column()
  declare activityType: string
  @column()
  declare actorId: number | null
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare logTimestamp: DateTime | null
}

export class ManagerSchema extends BaseModel {
  static $columns = ['managerStatus', 'userId'] as const
  $columns = ManagerSchema.$columns
  @column()
  declare managerStatus: string
  @column({ isPrimary: true })
  declare userId: number
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'notificationContent', 'notificationTimestamp', 'notificationType', 'readStatus', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notificationContent: string
  @column.dateTime()
  declare notificationTimestamp: DateTime | null
  @column()
  declare notificationType: string
  @column()
  declare readStatus: string | null
  @column()
  declare userId: number
}

export class PaymentSchema extends BaseModel {
  static $columns = ['feeId', 'id', 'modeOfPayment', 'paymentAmount', 'paymentStatus', 'paymentTimestamp', 'proofFileId'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare feeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modeOfPayment: string
  @column()
  declare paymentAmount: string
  @column()
  declare paymentStatus: string | null
  @column.dateTime()
  declare paymentTimestamp: DateTime | null
  @column()
  declare proofFileId: number
}

export class PhoneNumberSchema extends BaseModel {
  static $columns = ['contactNumber', 'id', 'isPrimary', 'userId'] as const
  $columns = PhoneNumberSchema.$columns
  @column()
  declare contactNumber: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrimary: boolean | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ReportSchema extends BaseModel {
  static $columns = ['id', 'landlordId', 'reportFileId', 'reportTimestamp', 'reportType', 'studentNumber'] as const
  $columns = ReportSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare landlordId: number
  @column()
  declare reportFileId: number
  @column.dateTime()
  declare reportTimestamp: DateTime | null
  @column()
  declare reportType: string
  @column()
  declare studentNumber: string
}

export class ReviewSchema extends BaseModel {
  static $columns = ['accommodationId', 'content', 'id', 'rating', 'studentNumber'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare accommodationId: number
  @column()
  declare content: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number
  @column()
  declare studentNumber: string
}

export class RoomSchema extends BaseModel {
  static $columns = ['accommodationId', 'id', 'roomAvailability', 'roomBuilding', 'roomCapacity', 'roomCurrentOccupancy', 'roomNumber', 'roomRent', 'roomStayType', 'roomType', 'tenantRestriction'] as const
  $columns = RoomSchema.$columns
  @column()
  declare accommodationId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomAvailability: string
  @column()
  declare roomBuilding: string
  @column()
  declare roomCapacity: number
  @column()
  declare roomCurrentOccupancy: number
  @column()
  declare roomNumber: string
  @column()
  declare roomRent: string
  @column()
  declare roomStayType: string
  @column()
  declare roomType: string
  @column()
  declare tenantRestriction: string
}

export class StudentSchema extends BaseModel {
  static $columns = ['college', 'degreeProgram', 'emergencyContactName', 'emergencyContactNumber', 'enrollmentProofFileId', 'form5Renewal', 'gender', 'studentNumber', 'userId', 'yearLevel'] as const
  $columns = StudentSchema.$columns
  @column()
  declare college: string
  @column()
  declare degreeProgram: string
  @column()
  declare emergencyContactName: string | null
  @column()
  declare emergencyContactNumber: string | null
  @column()
  declare enrollmentProofFileId: number
  @column()
  declare form5Renewal: boolean | null
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare studentNumber: string
  @column()
  declare userId: number
  @column()
  declare yearLevel: string | null
}

export class SysVariableSchema extends BaseModel {
  static $columns = ['currentSemester', 'currentSy', 'id', 'semStartDate', 'uplbLatitude', 'uplbLongitude'] as const
  $columns = SysVariableSchema.$columns
  @column()
  declare currentSemester: string
  @column()
  declare currentSy: string
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare semStartDate: DateTime
  @column()
  declare uplbLatitude: string
  @column()
  declare uplbLongitude: string
}

export class UserSchema extends BaseModel {
  static $columns = ['accountStatus', 'email', 'facebookAccount', 'fname', 'id', 'lname', 'mname', 'otpCode', 'otpExpiresAt', 'pfpFileId', 'role', 'suffix'] as const
  $columns = UserSchema.$columns
  @column()
  declare accountStatus: string | null
  @column()
  declare email: string
  @column()
  declare facebookAccount: string | null
  @column()
  declare fname: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lname: string
  @column()
  declare mname: string | null
  @column()
  declare otpCode: string | null
  @column.dateTime()
  declare otpExpiresAt: DateTime | null
  @column()
  declare pfpFileId: number | null
  @column()
  declare role: string
  @column()
  declare suffix: string | null
}
